data/resources.json
=> Add new resource for build modern website

app/templates/contact.html
I think it looks better centered, but can make another PR with it right justified
=> added Marketing Contact centered

app/static/scss/client/client.scss
Review: @RaymondXu @bluemelodia 
Check it out, it's super pretty
=> Added more spacing to the callouts

app/templates/base.html
=> Removed comments from <head>

app/static/scss/admin/navbar.scss
=> fixed content too wide

app/static/scss/admin/events/create.scss, app/static/scss/admin/events/events.scss, app/static/scss/admin/forms.scss, app/static/scss/admin/modal.scss, app/static/scss/admin/posts/edit.scss, app/static/scss/admin/utils.scss, app/templates/admin/events/create.html, app/templates/admin/events/edit.html, app/templates/admin/posts/edit.html
Review: @eunicekokor @RaymondXu
Events:
Blog posts:
=> Make the event and blog post edit screens responsive

app/routes/client.py, app/static/scss/client/single_event/single_event.scss, app/templates/events/event.html
=> Added a link leading to the feedback survey

app/templates/contact.html
=> updated contact page partnerships contact

app/routes/admin/auth.py, app/routes/admin/events.py, app/routes/admin/media.py, app/routes/admin/posts.py, app/routes/admin/users.py, app/routes/admin/whitelist.py, app/routes/base.py, app/static/scss/admin/admin.scss, app/templates/admin/admin.html, config/flask_config.py
Review: @eunicekokor @RaymondXu @natebrennand
Closes #191 
- **Implements categories for flashes**: Flashes categorized as `ERROR_FLASH` show up as red, and flashes categorized with `MESSAGE_FLASH` show up as green.
- **Flash an error on 500 in Eventum**: if a route that starts with `/admin` 500s, then an error will be flashed and we redirect to `/admin/home`.
=> Implement better flashes

app/static/scss/client/_colors.scss, app/static/scss/client/client.scss, app/templates/labs.html, data/labs_data.json
Fixes #166 and adds links to GitHub for Labs Projects
=> Update Labs page copy

.travis.yml, app/routes/blog.py, config/requirements.txt, test/base.py, test/test_routes.py
Review: @eunicekokor @RaymondXu @natebrennand 
Closes #200, adding some basic routes tests
Also closes #184
=> Write some basic routes tests

app/lib/events.py, app/models/Event.py, app/static/js/admin/events/create.js, app/static/scss/admin/events/events.scss, app/templates/admin/events/events.html, test/test_models/test_event.py
- Fixes #207 
- Closes #198 
- Makes events more attractive 
- Cleans up `Event.human_readable_datetime`
=> Pretty Events

app/forms/CreateBlogPostForm.py, app/routes/admin/posts.py, app/static/js/admin/posts/edit.js, app/static/scss/admin/posts/edit.scss, app/static/scss/client/blog/post.scss, app/templates/admin/posts/edit.html, app/templates/admin/posts/preview.html, app/templates/blog/post.html
=> created preview page

app/static/js/home/home.js, app/static/scss/client/client.scss
Fixes the parallax scrolling so that it doesn't mess up if you reload half way down the page.
Lessons learned:  
- `background-attachement: fixed` is borked in chrome: http://stackoverflow.com/questions/20268962/fixed-attachment-background-image-flicker-disappear-in-chrome-when-coupled-with
- `position: fixed` to the rescue!
=> move to position: fixed

app/routes/blog.py, app/routes/client.py, app/static/js/home/home.js, app/static/js/resources/resources.js, app/static/scss/client/client.scss, app/static/scss/client/components/footer.scss, app/static/scss/client/components/pagination.scss, app/static/scss/client/components/triple.scss, app/static/scss/client/resources/resources.scss, app/static/scss/common/utils.scss, app/templates/blog/blog.html, app/templates/contact.html, app/templates/events/events.html, app/templates/index.html, app/templates/labs.html, app/templates/page.html, app/templates/resources.html
Review: @evantarrh @eunicekokor @RaymondXu 
- **Closes #213**.  This was the general motivation of this PR.  The section spacing is more consistent now.
- **Closes #181**.  This was a one-liner fix, removing padding from `.small.event` elements on mobile.
- **Fixes the next button not showing up on the blog post page**. We were slicing blog posts to length 10 before checking if the blog posts have length great than 10.  The check was meant to look at *all* blog posts, but instead it was looking at the posts just on this page.
- **Fixes the background image showing through on the blog / resources pages**.  To do this, I combined the `<section class="tagline">` and the `<section class="card top-card">` into one section, which has a `<div class="top-card">` element inside of it, which is …
=> Styling cleanup

app/templates/events/archive.html, app/templates/jobfair.html
=> fix broken titles

app/static/scss/client/client.scss, app/templates/events/events.html, app/templates/page.html
- Removed jhil's creds (even though he's a :star2:) #230 
- Fixed spelling err #229 
- Played around with title overflow stuff for the mobile view. Changing heights doesn't do much. Easy solution is to push it up by 2em, but open to anything #221 
mobile
desktop
=> squashing issues pt. 1

app/templates/jobfair.html, app/templates/resources.html
=> fixes to resources, jobfair page

app/templates/labs.html, config/flask_config.py
=> Update Labs page and fix flask_config

app/routes/client.py, app/templates/foundry.html
@danrschlosser @RaymondXu 
Can I get this into the website before tomorrow evening?
=> added foundry route and html file

app/templates/contact.html, app/templates/jobfair.html, data/companies.json
@samw7823 @anshulkgupta give me a thumbs up and this will be live
=> added updated career fair companies

app/routes/admin/api.py
@jettca is this what you wanted?
=> api-change

app/templates/contact.html, data/resources.json
edited two links for #262 and #258.
=> fixing broken links

.gitignore, config/flask_config.py
=> images now properly stored/deleted in adi-website

app/templates/jobfair.html
Updating info so that we can send adicu.com/jobfair to prospective companies and the information will actually be correct. Temporarily viewable at [http://1346de5d.ngrok.io/jobfair](http://1346de5d.ngrok.io/jobfair)
=> Update jobfair.html date & time (pre-registration)

app/routes/client.py, app/templates/base.html, app/templates/foundry.html, app/templates/index.html, app/templates/jade.html, app/templates/labs.html, app/templates/mentorship.html, data/labs_data.json, data/resources.json
@evantarrh @mjp2220 @alanhdu 
Closes #290 #263
-Update program applications, descriptions, and dates
-Update mission statement on home page
-Add intermediate java resource
=> Update program applications, descriptions, and dates

app/templates/foundry.html, app/templates/resources.html
=> Update foundry application. Update devfest resources blurb.

app/routes/client.py
I removed the labs and foundry routes, but decided to keep the html + data json files to use them when we're ready to update the website with the new info
=> removed foundry and labs routes
